### ISSUE TITLE
scala file in jacoco report converted to java file in cobertura

### ISSUE THREAD

**Issue by emersonding** [kageiit/gradle-jacobo-plugin#4]
I'm generating jacoco report to cobertura report with jacobo that contains some scala classes, and found all scala file are became same class name with java suffix in cobertura report. 
Here's the sample:
sample jacoco xml report

>       <sourcefile name="**ScalaApp.scala**">
>          <line nr="7" mi="0" ci="2" mb="0" cb="0" />
>          <line nr="9" mi="0" ci="5" mb="0" cb="0" />
>          <counter type="INSTRUCTION" missed="0" covered="10" />
>          <counter type="LINE" missed="0" covered="2" />
>          <counter type="COMPLEXITY" missed="0" covered="3" />
>          <counter type="METHOD" missed="0" covered="3" />
>          <counter type="CLASS" missed="0" covered="1" />
>       </sourcefile>

will be convert to cobertura xml report 

> class name='ScalaApp$' filename='**ScalaApp.java**' line-rate='1.0' branch-rate='0.0' complexity='3.0'

here's used build.gradle was used

> plugins {
>     id "java"
>     id "application"
>     id "scala"
>     id "jacoco"
>     id "net.saliman.cobertura" version "2.5.2"
>     id "com.kageiit.jacobo" version "2.0.8"
> }
> 
> import com.kageiit.jacobo.JacoboTask
> repositories {
>     jcenter()
>     maven {
>         url "https://plugins.gradle.org/m2/"
>     }
> }
> dependencies {
>     compile 'com.google.guava:guava:21.0'
>     compile 'org.scala-lang:scala-library:2.11.8'
>     testCompile 'junit:junit:4.12'
>     testCompile 'org.scalatest:scalatest_2.11:3.0.1'
>     testRuntime "org.slf4j:slf4j-api:1.7.10"
> }
> mainClassName = 'App'
> task hello {
>     doLast {
>         println "Hello World!"
>     }
> }
> jacoco {
>     toolVersion = "0.7.9"
> }
> jacocoTestReport {
>     reports {
>         xml.enabled true
>         csv.enabled false
>         html.destination file("${buildDir}/reports/jacoco/jacocoHtml")
>     }
> }
> test.finalizedBy(project.tasks.jacocoTestReport)
> project.tasks.create("jacobo", JacoboTask, {
>     it.jacocoReport = file("${project.buildDir}/reports/jacoco/test/jacocoTestReport.xml")
>     it.coberturaReport = file("${project.buildDir}/reports/cobertura/cobertura.xml")
>     it.srcDirs = sourceSets.main.java.srcDirs
> })
>

**Comment by EmersonDing** [comment]
#

**Comment by emersonding** [comment]
@kageiit our project need this feature for test coverage. You can fix it when you have more time. Thanks!
